# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.16.1

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm ci --unsafe-perm
          - npm run build
